apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    tier: data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
data:
  DB_PWD: MTIzNDU2Nzg5 # base64 for '123456789'